### ISSUE TITLE
Error with raphael

### ISSUE THREAD

**Issue by macsee** [pierresh/morris.js#10]
Hi,
I'm gettin the following error when graphing a line graph with two lines. 

> Error: <path> attribute d: Expected moveto path command ('M' or 'm'), "H20".

I don't know why is this error happening since the graph seems to be displayed correctly. How can I get rid of this? Does it have something to do with the two lines in the same graph?
Thanks!

P.S.: Awesome work btw.

**Comment by pierresh** [comment]
Hello,

Thanks a lot for your message. Could you please give me your dataset so that I could try to reproduce that issue?

**Comment by macsee** [comment]
Hello. Thanks for replying.

This is my Morris object:

```
Morris.Line({
                      element: 'valores_graph',
                      lineColors: ['#0B62A4', '#7BB661'],
                      data: data_valores,
                      xkey: 'date',
                      ykeys: ['valor_pesos', 'valor_dolar'],
                      labels: ['Valor Pesos', 'Valor Dólares'],
                      parseTime: false,
                      nbYkeys2: 1,
                      animate: false,
                      dataLabels: false
                });
```

And this is my data:

```
data_valores =
[
  {
    "date": "2017-10-23",
    "valor_pesos": 7443150,
    "valor_dolar": 429000,
    "valor_cotiz": 17.35
  },
  {
    "date": "2017-08-05",
    "valor_pesos": 7550400,
    "valor_dolar": 429000,
    "valor_cotiz": 17.6
  },
  {
    "date": "2017-07-14",
    "valor_pesos": 7293000,
    "valor_dolar": 429000,
    "valor_cotiz": 17
  }
]

```
Thanks!

**Comment by pierresh** [comment]
Thanks for your prompt reply. I just tested and it works fine (I use Raphael js 2.2.7 and the latest version of my fork - the master), I do not get any message in the console:

<img width="1401" alt="wechat145bac0e027e5c0fca32b20a4a9369e4" src="https://user-images.githubusercontent.com/7520095/53085843-be644e80-353e-11e9-8f37-87d6d71e256e.png">

**Comment by macsee** [comment]
Hmmm. That's weird. I will check my libraries version. Where can I get Raphael 2.2.7? I've only found 2.2.0 in its github repository. 
Thank you.

**Comment by macsee** [comment]
You're right! I've isolated my code from the rest of my app and it works fine :)
I'm loading a bunch of other libraries so it may be something to do with that.
I'm closing this thread since it's not a Morris bug.
Thank you so much for your time.

Cheers!
