### ISSUE TITLE
DONUT chart NO labels/ hover info

### ISSUE THREAD

**Issue by MR-AMDEV** [pierresh/morris.js#11]
Hi i really appreciate the hard work on this plugin.
This should be living and should gets updated !
While i was using Donut chart , in the default Morris donut , the labels are shown  in the center of like so :
<img width="263" alt="morris" src="https://user-images.githubusercontent.com/20532497/55755313-1b24b580-5a68-11e9-9808-cae0055cfcba.PNG">
But while using the following options:
      donutType: 'pie',
      dataLabels: true,
i get a nice look but there is no info that represents the colors for a label it just only shows the value not the labels and not even on hover , like so 
<img width="260" alt="morrise" src="https://user-images.githubusercontent.com/20532497/55755292-13fda780-5a68-11e9-9fd9-05af16448f61.PNG">
**So it would be very difficult for using just by colors and values .Labels are very important for easy reading**
**PS** I am using the examples given in the source code.

**Comment by pierresh** [comment]
Hello,

Thanks for your message. Actually, this is on purpose because this is quite difficult to place elegantly data labels on pie chart. There are always problems of length, overlapping, and so on. I suggest you to add a legend below the pie chart. That is possible like this:

````js
var pie_data = [
	{label: 'Africa', value: 5 },
	{label: 'Asia', value: 5 },
	{label: 'Europe', value: 14 },
	{label: 'North America', value: 3 },
	{label: 'South America', value: 5 }
];

Morris.Donut({
	element: 'chart_line_1',
	data: pie_data,
	donutType: 'pie',
	dataLabels: true,
}).options.colors.forEach(function(color, a){ 
	if (pie_data[a] != undefined) {
	var node = document.createElement('span');
	node.innerHTML += '<span style="color:'+color+'"><i style="margin-left: 15px;" class="fa fa-square"></i> '+pie_data[a].label+'</span>';
	document.getElementById("chart_line_1").appendChild(node);
	}
});
````

Final result:

![Screen Shot 2019-04-10 at 08 47 51](https://user-images.githubusercontent.com/7520095/55843964-9ae87800-5b6d-11e9-9042-fb7a7279ba10.jpg)

**Comment by MR-AMDEV** [comment]
Thanks for that ! This should be documented.
