### ISSUE TITLE
Donut: Show percentage in the center

### ISSUE THREAD

**Issue by Julien-Delattre** [pierresh/morris.js#12]
Regarding the donut chart, I would like to see the percentage in the center.
It seems that the only way to display the percentage is to enable the property "dataLabels".

In "morris.donut.coffee", the method "select" uses row.value instead of the calculated finalValue:
`@setLabels(row.label, @options.formatter(row.value, row))`

Any chance to get an option for that? 

Below, a quick test. Please correct me if I'm mis-using it.
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Vue-morris examples</title>
    <link rel="stylesheet" href="https://pierresh.github.io/morris.js/css/morris.css" />
    <script src="https://pierresh.github.io/morris.js/js/morris.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js"></script>
  </head>
  <body>
    <h1>Test showPercentage on Donut</h1>
    <div id="chart_donut"></div>
    <script>
      Morris.Donut({
        element: "chart_donut",
        showPercentage: true,
        dataLabels: true,
        data: [{ label: "Asia", value: 300 }, { label: "Europe", value: 250 }],
      });
    </script>
  </body>
</html>
```

Thanks for your great job by the way!

**Comment by pierresh** [comment]
Hello,

thanks for your message, I may add that option soon. The settings above look fine.

**Comment by pierresh** [comment]
Hello,

I  just pushed a commit, now the value in the center would be the percentage of selected segment if the options `showPercentage` is set to **true** and `dataLabels` set to **false**.

Example:
```js
    Morris.Donut({
      element: 'chart_test',
      showPercentage: true,
      dataLabels: false,
      data: [{ label: "Asia", value: 300 }, { label: "Europe", value: 250 }],
    });
```

Result:
![image](https://user-images.githubusercontent.com/7520095/62816793-2e06de00-bb5f-11e9-9a07-81730144aeac.png)
