### ISSUE TITLE
Donut 0 value when compared to lines and bar

### ISSUE THREAD

**Issue by techgasp** [pierresh/morris.js#13]
Hi there,
Great job with fork, I'm using it on a project to display graph data.
I've seen people complaining about this in several places "impossible to display donut graph with 0 data values (just displays empty space as you know)
But it's weird the same data... with 0 values is displayed in both lines and bars graphs, these graphs get generated with 0 vales... awesome.
It would be great if donut graphs worked the same way, the graph would be generated qith 0 vales.
[![donut.png](https://i.postimg.cc/RVcv8gJF/donut.png)](https://postimg.cc/gn29LqDF)

**Comment by pierresh** [comment]
Hello,

thanks for your message, so far it works well if at least one value is not equal to 0. But actually, I am not really what should be shown if every value is equal to 0. Probably better to display a message ("_No data for this chart_") like when the data array is empty

```js
Morris.Donut({
	element: 'chart_donut',
	data: [
		{label: 'Label 1', value: 1 },
		{label: 'Label 2', value: 0 }
	],
	donutType: 'pie',
	dataLabels: true,
	dataLabelsPosition: 'outside'
});
```
![image](https://user-images.githubusercontent.com/7520095/61184246-116da800-a67e-11e9-9e6f-ac16159dee3a.png)

**Comment by techgasp** [comment]
"I am not really what should be shown if every value is equal to 0"
Design wise it sucks not to have the graph. If all values = 0 maybe it should generate a graph with just 1 slice with value 0... Almost like your screenshot without the green. Or more complex all slices the same size with value 0.

It think people complain about this not because of values, the graph is correct... it's just because of design and display like my screenshot.

**Comment by pierresh** [comment]
Hello,

I just published a quick commit in order to display segments of pie charts even if the total value is equal to 0. This works for both pie and donut charts.

![image](https://user-images.githubusercontent.com/7520095/61216414-e186d900-a73f-11e9-83c1-ac2ae4f179d6.png)

**Comment by techgasp** [comment]
You are awesome.
[![Screenshot.png](https://i.postimg.cc/WpFYn1t6/Screenshot.png)](https://postimg.cc/vDyv8Mrc)

**Comment by pierresh** [comment]
If you like this plugin, please star it :)
