### ISSUE TITLE
I think it's still depending on some jQuery

### ISSUE THREAD

**Issue by Xdabier** [pierresh/morris.js#15]
It's shows me this error 
![image](https://user-images.githubusercontent.com/20482799/81670045-f7882780-943e-11ea-8c50-7d04b450c1db.png)

when I hover on the Area graph.
and it doesn't show the tooltip

I'm using it on Angular 9.1.4
and the morris.js06 version is 0.6.5

**Comment by pierresh** [comment]
Thanks a lot for your comment, you are right, I introduced a dependency to jquery because I wanted to apply that [pull request](https://github.com/morrisjs/morris.js/pull/464).. Sorry for this, I need to find another way to escape labels. I just committed a fix in master branch.

**Comment by pierresh** [comment]
I just published a commit, now labels are escaped without needing jquery. I will publish a new version on npm a bit later.

**Comment by Xdabier** [comment]
Thanks a lot @pierresh ! so can I use the new commit now, or should I wait for the npm version ?

**Comment by Xdabier** [comment]
I just tested the commit right now, and it works fine thanks!

**Comment by pierresh** [comment]
You are welcome, for your information, I just published the version 0.6.6 on npm.
