### ISSUE TITLE
Stacked bar charts with negative values

### ISSUE THREAD

**Issue by jrtraynor** [pierresh/morris.js#16]
With ref to 
https://github.com/morrisjs/morris.js/pull/533 
and 
https://github.com/morrisjs/morris.js/issues/579

If you have  stacked bar chart and one value is negative you end up with a floating bar eg :
![image](https://user-images.githubusercontent.com/65301215/81836736-cb9e9c00-953b-11ea-92f1-867eb2b12877.png)

There's a patch to the original morris chart that supposedly fixed the issue

**Comment by pierresh** [comment]
Thanks for your message, I just committed the fix.
