### ISSUE TITLE
barColors as a function + nbYkeys2=1  createserror

### ISSUE THREAD

**Issue by jrtraynor** [pierresh/morris.js#17]
If you have nbYkeys2 set to 1 and use a function for barColors  eg
xkey:'lb',
ykeys:['cost','budget'],
parseTime:false,
dataLabels:false,
gridIntegers: false,
stacked:false,
nbYkeys2: 1,
animate:false,
labels:['".t("Spend")."','".t("Budget")."'],
barColors: function (row, series, type){
if(type==='bar'){
	if(row.y<0){
		return 'red';
	} else if(row.y>100){
		return 'red';
	} else {
		return 'green';
	}
}
}
you then get attr errors when the code references "this.options.barColors[nb + ii]" in the drawBarLine function ( 4 of them) and the graph fail to draw

Thanks

James

**Comment by pierresh** [comment]
Hello, 

Ok thanks for your feedback, I will check a bit later today.
