### ISSUE TITLE
Horizontal stacked barchart not display third color

### ISSUE THREAD

**Issue by wmartey2012** [pierresh/morris.js#18]
Hello,
The stacked horizontal bar chart does not display the third color when you have more than two colors.
Kindly help to address it
![2020-06-051](https://user-images.githubusercontent.com/66465051/83853772-486d0200-a705-11ea-970f-ffc288162968.png)

.

Thanks

**Comment by pierresh** [comment]
Hello,

Thanks for your message and sorry for this. Could you please give me your code and dataset? So that I could reproduce easily your chart, thanks.

**Comment by wmartey2012** [comment]
Morris.Bar({
                            barSizeRatio: 0.1,
                            element: 'month_year_container',
                            data: [{"y": "WMartey", "a": 5, "b": 30, "c": 4}],
                            xkey: 'y',
                            ykeys: ['a', 'b', 'c'],
                            labels: ['insert', 'update', 'delete'],
                            lineColors: ['#ff6c60', '#1e88e5', '#7A92A3'],
                            lineWidth: '3px',
                            resize: true,
                            redraw: true,
                            stacked: true,
                            horizontal:true,
                            barColors: ['#5CB85C', '#f0ad4e', '#A02529']
                        })

**Comment by pierresh** [comment]
Hello,

Thanks for your feedback, I just committed a fix, please have a check.

**Comment by wmartey2012** [comment]
Excellent, it worked
