### ISSUE TITLE
Charts hover labels order

### ISSUE THREAD

**Issue by Demitrius** [pierresh/morris.js#2]
Stacked bar hover labels order looks good, but Line charts hover label order reversed :(

I can change data order in options, but this will effect line color order in chart, that is not good.

**Comment by pierresh** [comment]
Hello,

For me the order is ok. Can you show me a screenshot of the chart and give me your code for Morris chart line, so that I could try to reproduce the problem

**Comment by Demitrius** [comment]
![image](https://user-images.githubusercontent.com/2479194/36217297-1f05bb44-11c2-11e8-9985-1efd56efc540.png)


Code

Morris.Line({
            element: 'chart_x1',
            data: x.cdd,
            xkey: 'tt',
            ykeys: ['chats', 'cfs', 'ord'],
            labels: ['Chats', 'Calls from Website', 'Forms'],
            redraw: true,
            dateFormat: __f,
            xLabels: __i,
            lineColors: ['#00D000', '#359ade', '#7A92A3'],
            lineWidth: 2,
            pointSize: 3,
            pointSizeGrow: 2
        });

As you can see in screen, "Chats" the last, but I expect it on the top

I use latest code version

morris.js06 v0.6.1
Copyright 2018 Olly Smith All rights reserved.
Licensed under the BSD-2-Clause License.

**Comment by pierresh** [comment]
Ok, I see. Actually there was no any line code in this plugin to order the content of the hover per points value. I just added the option _hoverOrdered_ for this in master. So far I keep it **false** by default as I never got this feedback before and this may also influence the Area chart. Just set it to **true** to have the content of hover ordered according to points value.

**Comment by Demitrius** [comment]
Thank you, it is good option!

Could add another one option hoverReversed and some code to reverse order?
Its will meet my requirements for charts at this time.

... line 1327
} else {
        _ref2 = row.y;
        for (jj = _k = _ref2.length - 1; _k >= 0; jj = _k += -1) {
          yy = _ref2[jj];
          order.push(jj);
        }
        **_if (...hoverReversed) {
            order = order.reverse();
        }_**
      }
...

**Comment by pierresh** [comment]
Ok, now it is possible to set the option _hoverOrdered_ to **'reverse'**.

**Comment by Demitrius** [comment]
This reverse implementation do reverse array which already order by row values.

I need two separate options, one sort by value and one in-depended reverse.

Sometimes useful make reverse without order by values, sometimes need only order by values and sometimes, need reversed order by values. This will very flexy.

**Comment by pierresh** [comment]
Ah ok I see, ok so now I just added the option _hoverReversed_, that is **false** by default.

**Comment by Demitrius** [comment]
Works very well from the box! Thank you!!!

Summary. New options:
BOOLEAN **hoverOrdered** - Order hover items by value.
BOOLEAN **hoverReversed** - Reverse hover items order.
