### ISSUE TITLE
Donut, percentage not showing outside chart

### ISSUE THREAD

**Issue by kori22** [pierresh/morris.js#20]
hi, 

i am using morris.js for my project, it's work amazing. but i found some problem for showing percentage of data. when load page for the first time, the percentage are not showing, but after i run inspect element on my browser, percentage will show

please help me regarding this issue, bellow i attach some screenshot 

before running inspect element:
<img width="392" alt="Screen Shot 2020-10-09 at 23 30 51" src="https://user-images.githubusercontent.com/6101157/95608642-a2048500-0a87-11eb-9ea3-08c7f1fd7b80.png">

after running inspect element
<img width="377" alt="Screen Shot 2020-10-09 at 23 31 12" src="https://user-images.githubusercontent.com/6101157/95608653-a4ff7580-0a87-11eb-8fe0-4e6b47a4232d.png">

**Comment by pierresh** [comment]
Hello,

Thanks for your message and I am sorry for my late answer. Could you please give me your code so that I could reproduce your problem?

**Comment by kori22** [comment]
hi Pierresh,

below my code to generate donut chart

var employment = [
  {
    label: 'probation',
    value: 7
  },
  {
    lable: 'permanent',
    value: 1
  }
]




window.areaChart = Morris.Donut({
    element: 'employement-summary-chart',
    data: employment,
    dataLabels: true,
	dataLabelsPosition: 'outside',
	showPercentage: true,
	parseTime: false,
    resize: false
})

**Comment by pierresh** [comment]
Sorry, for me it works well on my computer.

Nevertheless, there is a workaround for such kind of display problem by triggering a screen resize event with the following command:

```
window.dispatchEvent(new Event('resize'));
```
