### ISSUE TITLE
belowArea: false - filler ignores smooth: false  

### ISSUE THREAD

**Issue by noppingen** [pierresh/morris.js#24]
Hello.

When setting `smooth: false` and `belowArea: false` the filler routine somewhat ignores `smooth: false`:

![2021-12-14 06_09_29-wetter onderka com _ Archiv](https://user-images.githubusercontent.com/11265876/145937104-14fda207-cef6-46fe-befa-cafc9c04bf41.png)

Lines are drawn correctly, but the filling is still smoothed. See https://wetter.onderka.com/history/, most obvious in sections "Verlauf Luftdruck" (air pressure) and "Verlauf Luftfeuchtigkeit" (humidity). 

Easy fix?

**Comment by pierresh** [comment]
Hello,

Thanks for your message, indeed I found a problem with the option **belowArea**, I just committed a fix, please have a check. Also, **smooth** is kind of deprecated, you need to set the option **lineType** to _'jagged'_ , and it will work as you expect.

<img width="1415" alt="WX20211214-214349@2x" src="https://user-images.githubusercontent.com/7520095/146009988-5f4c2a4e-d82a-4b5b-baea-523ec7dc419b.png">

**Comment by noppingen** [comment]
Yes, works - Thanks!

For the record, the URL is https://wetter.onderka.com/archive/ now.
