### ISSUE TITLE
Z order to control lines visible color when lines cross each other

### ISSUE THREAD

**Issue by Demitrius** [pierresh/morris.js#3]
How can I manually set lines "z index order" on the chart?
When two lines on the same position and cross each other, first line color will above, second line will under.

Now this order depends on sequence colors/data in options, but I need choose my custom sequence.

**Comment by pierresh** [comment]
Hello,

You can already control the sequence of data by colors, this is linked with the order of elements in _ykeys_.

Also, I just added the option _pointSuperimposed_. If you set it to **false**, redundant points would be offseted (default is **true**). You can check it in the latest version in master.

![image](https://user-images.githubusercontent.com/7520095/36204470-5ed6d330-11c6-11e8-9ce0-bc74adf8d871.png)

**Comment by Demitrius** [comment]
![image](https://user-images.githubusercontent.com/2479194/36254911-f1c586cc-125d-11e8-94ec-433a71fdd8a2.png)

This option not works properly, see it in screen 1. Code below.

Code is:
Morris.Line({
            element: 'chart_x1',
            data: x.cdd,
            xkey: 'tt',
            ykeys: ['coeshows', 'coedecline', 'coechats', 'coecfs', 'coelam'],
            labels: [JCC.La[23][0], JCC.La[23][1], JCC.La[23][2], JCC.La[23][3], JCC.La[23][4]],
            redraw: true,
            dateFormat: __f,
            lineWidth: [1, 1, 2, 2, 2],
            xLabels: __i,
            pointSize: 3,
            lineColors: ['#63CFD8', '#1FB2BE', '#00D000', '#359ade', '#7A92A3'],
            dataLabels: false,
            pointSuperimposed: false,
            hoverOrdered: false,
            hoverReversed: true
        });

If i set _pointSuperimposed_ true, chart looks like screen 2

![image](https://user-images.githubusercontent.com/2479194/36255016-50f1dac4-125e-11e8-861c-776cbefe3ed3.png)

**Comment by Demitrius** [comment]
Does it difficult add order when paths drawing?

**Comment by pierresh** [comment]
It did not work because your settings of _lineWidth_ is an array. Now it should be ok.

As I wrote above, the order of paths is defined by the order in _ykeys_. I would rather do not modify the current design.

**Comment by Demitrius** [comment]
Looks better! Thank you!

![image](https://user-images.githubusercontent.com/2479194/36259063-0449238e-126e-11e8-8e85-89b0d6893427.png)
