### ISSUE TITLE
Ymin and Ymax for right Y-axis

### ISSUE THREAD

**Issue by gumilar1995** [pierresh/morris.js#5]
Hello, 

is there any configuration to set up ymin and ymax only for right y-axis?
thanks.

**Comment by pierresh** [comment]
Hello,

Yes, there are _ymin2_ and _ymax2_ but it seems these 2 options do not work.. I am going to check them.

**Comment by gumilar1995** [comment]
Thanks a lot for your help and response.

**Comment by pierresh** [comment]
Hello, I just updated the master, it should be ok now.

**Comment by gumilar1995** [comment]
it works perfectly, thank you
