### ISSUE TITLE
Tooltip vertical alignment issue

### ISSUE THREAD

**Issue by sveldhuisen** [pierresh/morris.js#8]
I'm having issues with the dynamic alignment of the tooltip within a area chart. The tooltip always ends up at the bottom of the area chart and does not follow the dots of the graphs on the y axis (x axis works ok). When using Browser developer tools I see that the Morris JavaScript does not update the element style property "top" for <div class="morris-hover morris-default-style">

My code:

```
var morrisChart =  Morris.Area({
     element: chartItem.element,
     data: chartItem.data,
     xkey: chartItem.xkey,
     ykeys: chartItem.ykeys,
     labels: chartItem.labels
 });
```

I'm using 0.6.3 from https://www.npmjs.com/package/morris.js06. When I revert back to the original MorrisJs (0.5.1) vertical alignment works ok again.

**Comment by sveldhuisen** [comment]
Attached a screenshot of the issue.
<img width="756" alt="screen shot 2019-01-28 at 13 50 58" src="https://user-images.githubusercontent.com/18281276/51837500-d829c180-2303-11e9-9628-683078632cbf.png">

**Comment by pierresh** [comment]
Hello,

Thanks for your message, could you please give me your dataset? I tried to reproduce your problem but it seems working fine for me.

<img width="855" alt="screen shot 2019-01-28 at 21 12 59" src="https://user-images.githubusercontent.com/7520095/51838568-a20b3280-2341-11e9-9872-4146d14e7519.png">

**Comment by sveldhuisen** [comment]
Hi Pierre,

thanks for your quick response. This is my full Javascript init of Morris.js:

```
        var morrisChart =  Morris.Area({
             element: 'morris-area-chart',
             data: [{"day":"2019-01-28T04:00:00.000Z","ERROR":234,"INFO":6},{"day":"2019-01-28T05:00:00.000Z","ERROR":234,"INFO":1},{"day":"2019-01-28T06:00:00.000Z","ERROR":234,"INFO":1},{"day":"2019-01-28T09:00:00.000Z","ERROR":239,"INFO":62},{"day":"2019-01-28T10:00:00.000Z","ERROR":252,"INFO":80405,"WARN":4719},{"day":"2019-01-28T13:00:00.000Z","ERROR":29},{"day":"2019-01-28T07:00:00.000Z","ERROR":233,"INFO":1},{"day":"2019-01-28T08:00:00.000Z","ERROR":235,"INFO":197},{"day":"2019-01-28T11:00:00.000Z","ERROR":243,"INFO":263},{"day":"2019-01-28T12:00:00.000Z","ERROR":233,"INFO":9}],
             dataLabels: false,
             xkey: 'day',
             ykeys: ["INFO","WARN","ERROR","FATAL"],
             labels: ["Informatief","Waarschuwingen","Fouten","Fatale fouten"],
             pointSize: 2,
             hideHover: 'auto',
             resize: true,
             hoverOrdered: true,
             lineColors: ['#279835', '#dfd952', '#f29111', '#CA455E'],
             dateFormat: function(d){
                 return jQuery.timeago(d);
             }
         });
```

**Comment by sveldhuisen** [comment]
Could it be that there is some kind of weird interaction with other JavaScript components (i.e. I'm using startbootstrap-sb-admin-2, timeago, metismenu, raphael, jquery-steps, datatables.net etc)?

**Comment by pierresh** [comment]
Actually this is is because you have some null values in your dataset. I will do a fix tomorrow morning for this. For the time being, a workaround is to provide the value 0 for ykeys that have no values.

Example: change `{"day":"2019-01-28T04:00:00.000Z","ERROR":234,"INFO":6}` to `{"day":"2019-01-28T04:00:00.000Z","ERROR":234,"INFO":6,"WARN":0,"FATAL":0}`

**Comment by sveldhuisen** [comment]
Excellent Pierre, thanks for the effort!

**Comment by sveldhuisen** [comment]
I've modified my server side Elastic search template by adding "min_doc_count": 0. This results in a 0 value for the ykeys that have no values. The tooltip is now correctly rendered along the line of the chart.

**Comment by pierresh** [comment]
This problem has been fixed this morning.
