### ISSUE TITLE
Donut chart layout issue with dataLabelsPosition: 'outside'

### ISSUE THREAD

**Issue by sveldhuisen** [pierresh/morris.js#9]
Hi Pierre, I have a Donut Chart that is using dataLabelsPosition: 'outside' with showPercentage: true inside a responsive Bootstrap div. On small screens the width of the percentage is not taken into account.

The result is that the percentage are only partly visible. See attached screenshot.

<img width="431" alt="screen shot 2019-01-28 at 22 34 53" src="https://user-images.githubusercontent.com/18281276/51868048-52326880-234d-11e9-93d2-026519e1045a.png">

**Comment by pierresh** [comment]
Hello,

This problem is a bit difficult. It seems that there are some padding/margin in your container, maybe you can set them to 0 so that the element of the chart could be expanded a bit.

**Comment by sveldhuisen** [comment]
Hi Pierre, it seems to be related to padding. My Morris chart div is contained within a Bootstrap panel-body that has a padding of 15px. Do you have any suggestions on how to apply spacing without breaking the percentage labels?

**Comment by pierresh** [comment]
Hello,

I just published a commit to add a new option `padding`. Its default value is 0, you can try to set something like 3 or 5, this will slightly reduce the size of the donut generated so that hopefully the labels could be displayed completely.
